#ifndef QBARCODESCANNER_GLOBAL_H
#define QBARCODESCANNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QBARCODESCANNER_LIBRARY)
#define QBARCODESCANNER_EXPORT Q_DECL_EXPORT
#else
#define QBARCODESCANNER_EXPORT Q_DECL_IMPORT
#endif

#endif // QBARCODESCANNER_GLOBAL_H

